---
title: Tree life simulator
hero_image: images/banner.png
description: Create a simulation that shows the impact of land management and deforestation
  on trees, wildlife, and the environment
version: 4
listed: true
copyedit: false
last_tested: '2020-09-15'
steps:
- title: Introduction
- title: Grow some trees
- title: Tree management
  completion:
  - engaged
- title: Count the trees
- title: Human deforestation
- title: Monitor tree levels
- title: Natural deforestation
  completion:
  - internal
- title: Share your project
- title: What next?
