title: planting-trees
hero_image: images/banner.png
description: planting-trees description
version: 4
listed: false
copyedit: false
last_tested: "2020-09-15"
steps:
  - title: Introduction
  - title: Create a forest
  - title: Grow more trees
  - title: Count the trees
  - title: Human deforestation
  - title: The impact on CO2 levels
  - title: Natural deforestation
  - title: Share your project
  - title: What next?
